package com.astroganit.api.constant;

public class HoroscopeConstantEng2024 {

	   //"शिक्षा","विवाह","फाइनेंस","व्यापार","करियर","प्रेम","स्वास्थ्य"

    public static String[] ariesYH = {
            "Based on the Aries horoscope for 2024, this year, students will need to put in more hard work and effort to achieve good grades in exams. The educational sector will have favorable conditions, but students may need to work harder during this time. Success can be attained in competitive exams. The timing is favorable for higher education, and students may consider going abroad for their studies, although the choice of foreign educational institutions should be made carefully.\n" +
                    "\n At the beginning of the year, students may find their focus wavering from their studies. During this period, they might encounter obstacles in their studies, and exam-related stress could be prevalent. However, later in the year, the educational sector is likely to improve, and your hard work will yield positive results. If you encounter any difficulties in your studies, seeking assistance from your peers and teachers is advisable. Practice yoga and meditation to keep your mind stable.\n" +
                    "\n For students pursuing engineering and medical fields, this year could be particularly promising, so put in your best effort. Luck will be on your side.",
            "In 2024, your marital life will be in good shape. You will have a great opportunity to enjoy romance with your spouse. At the beginning of the year, your relationship will be filled with sweetness. The conditions for your married life will be even more favorable. During this time, you will empathize with your spouse's feelings, and your bond will grow stronger. However, during this period, some minor love-related issues may arise. Happiness will enter your marital life during this time. There is a possibility of receiving favorable news related to children. Nevertheless, you should take care of your spouse's health as they may be at risk of illnesses like fever, typhoid, and dengue. They should stay vigilant about these diseases.\n" +
                    "\n Towards the end of the year, there may be an improvement in your spouse's health. Additionally, it's important to encourage your children to study well. Along with their studies, praising their sports performance will also be appreciated. Although they may exhibit some stubbornness during this time and be argumentative, try to explain things to them with love.",
            "According to the 2024 horoscope, your financial situation may experience fluctuations this year. At the beginning of the year, your financial status might be strong, but there could also be an increase in your expenses. Sudden increases in your expenditures are possible. If you don't control these expenses, you may face financial difficulties.\n" +
                    "\n There could be a boost in your business in the months of June and July, which could lead to financial gains. However, if you are investing in the stock market, there is a possibility of financial losses, so it's advisable to seek advice from a financial expert before investing. In matters of money, avoid placing excessive trust in any individual or organization, as it could result in financial losses.\n" +
                    "\n You may benefit financially from international connections, and your international business ventures may be successful, with the potential for expansion. There is a possibility of entering into a deal with a foreign company that could increase your income. Your financial situation could gradually improve during this time, and you may have strong potential for higher earnings from various sources. This could be a unique year for your financial life.",
            "From a business perspective, you may have an opportunity to achieve positive results. Please refrain from engaging in unethical practices and avoid interfering in the affairs of others, as it could harm someone. You might also start something new. Whatever your goal is, you can attain it, but please continue your efforts.\n" +
                    "\n It's essential to remain vigilant in business. It's a favorable time for electronic markets, and you can consider investing in them. You can delegate tasks, but do so with caution and careful consideration.",
            "In the year 2024, individuals belonging to the Aries zodiac sign can expect mixed results in their career. Your hard work and efforts will lead to progress, and luck will favor your career advancement. Right from the beginning of the year, you may face challenges in your work, but as time goes on, you will reap the rewards of your efforts.\n" +
                    "\n If you are working in the private sector, you will need to put in dedicated efforts to achieve success. Your superiors or bosses will be impressed with your work. In terms of employment, you may have opportunities to work away from home. Software engineers can look forward to a favorable year, and there's also a possibility of overseas opportunities.\n" +
                    "\n Your seniors will support you, but be cautious of any colleagues who may conspire against you, so keep an eye on suspicious individuals. It's better to stay away from office politics, as it will be in your best interest. Avoid getting involved in disputes or conflicts that could negatively impact your reputation. In the middle of the year, there may be opportunities for business-related travel. If you are working in the government sector, there's a chance that the government might offer you a significant opportunity or reward this year.",
            "Based on the outlook for 2024, here is how the future may unfold for Aries individuals:\n" +
                    "\n In the year 2024, your love life is expected to remain stable. There are no major changes foreseen in your life. However, you may need to cultivate transparency in your relationship to keep it strong. There might be occasions when your ego clashes with your partner, which could lead to not only disagreements but also increased distances between you two. Thus, it's important to be serious and cautious about your love during this time. During this phase, your partner's nature may undergo changes, and misunderstandings over minor issues could arise. It's crucial to display patience and make an effort to understand your partner's feelings. If your partner becomes upset with someone, try to pacify them with love rather than imposing your opinions, as it could create obstacles in your relationship.\n" +
                    "\n On the flip side, February could bring a new dimension to your love life. During this time, you may have ample opportunities to meet your loved one. You may even initiate new relationships in your workplace or college with someone who touches your heart. The rest of the year looks promising for you. You might have a chance to embark on a delightful journey with your beloved. For those seeking true love, your search may be fulfilled this year. You could go on long drives with your love partner.",
            "According to the 2024 horoscope, individuals with the Aries zodiac sign can expect fluctuations in their health this year. Your health journey will be marked by ups and downs, but it's crucial to take your health seriously. At the beginning of the year, you will see improvements in your health. If you manage to reduce everyday stress, your health should remain good. You'll be energetic and work with enthusiasm. Improved health will enhance your personality, making you more attractive to others.\n" +
                    "\n During January and February, there will be improvements in your lifestyle, but maintaining a clean diet is essential for these changes. Be cautious of diseases like dysentery, fever, dengue, and typhoid during this period, so pay attention to your health and maintain cleanliness in your surroundings. Stay hydrated by consuming plenty of liquids to prevent dehydration.\n" +
                    "\n However, you might face health-related concerns during this phase, possibly due to personal issues causing mental stress. Do not let this stress overwhelm you. Your daily routine in the workplace will be busy. You may also experience weight-related complaints, so focus on physical exercise. Joining a fitness club is a good option. November and December will bring improvements in your health, and you'll feel fully fit during this time. Regular physical exercise is essential to maintain your fitness.",
                    ""
    };

    public static String[] taurusYH = {
            "According to the 2024 horoscope, this year, students of the Taurus sign will excel in their studies. This year holds the potential for success and prosperity in the field of education for you, but it will require significant hard work. You will fully concentrate on your studies and put in extra effort to achieve good grades in your exams. In January, you will display strong enthusiasm for your studies. If you face any difficulties in a particular subject, your classmates and teachers can assist you.\n" +
                    "\n Students preparing for board exams will need to put in extra effort from time to time, but luck will be on your side. The exam results will bring you much happiness. On the other hand, students preparing for competitive exams will see the fruits of their hard work in September-October. This year will bring several opportunities for students pursuing research in the field of science. Although the competition may be tough, careful and planned preparation will be essential.",
            "According to the 2024 horoscope, this year, your married life will be filled with sweetness. Although minor disagreements may occur with your spouse at times, their impact will be minimal, and you will successfully manage the situation. You will consistently receive support from your spouse in your married life. While negative emotions about your married life may occasionally cross your mind during this time, their influence will be limited. At times, you may contemplate keeping a distance from your spouse, but later, you might regret it. Before taking any steps to resolve conflicts during this period, think carefully.\n" +
                    "\n With time, you won't need to struggle to strengthen your married life. Don't let trust in your spouse waver because they are with you this year and actively involved in your relationship. This year, you will also benefit through your spouse. Regarding children's health, this year will be favorable. They will excel in their studies and follow your advice. However, remain vigilant in their upbringing. Pay special attention to their health, as any illness during this period can affect them. This year could bring improvements and prosperity in your children's health, and they might receive good news.",
            "This year, your financial life is likely to appear better than usual. There will be an improvement in your financial situation, but your expenses may also increase. It will be important to exercise restraint on unnecessary expenses to safeguard your financial stability. Particularly, your income may see growth, and new sources of income may open up. From April to May, and then from June to July, your financial situation could strengthen. The impact of this process may also be felt in July. Investing will be beneficial, and there could be an increase in ancestral property. If you have any pending property court cases, the decision may turn in your favor.\n" +
                    "\n Your successful efforts in your field could assist in strengthening your financial situation. Your money might go towards purchasing electronic gadgets. However, you will make effective use of digital media to expand your business. In the second phase of the year, be cautious about matters related to financial assets. If you are investing in the stock market, seek advice from financial experts. Consider forming partnerships in your business. This year, you may be able to purchase a new vehicle. There are possibilities of profit in the metal-related business, although achieving good results in agriculture could be a bit challenging.",
            "Achievement doesn't come from imagination but from hard work. If you become an entrepreneur, you will definitely reap the benefits of your diligence. This year, you may have the opportunity to work on a partnership, but it's best to make decisions gradually and thoughtfully, not in haste. If you are in a business partnership, remain cautious because trust may falter at times, partnerships may break, and work interruptions could occur. However, if you involve your life partner in your business, you will indeed benefit. All your efforts will succeed in some way, so don't worry, just continue to work honestly and diligently.",
            "According to the upcoming year 2024, individuals born under the Taurus sign may face challenges in their careers. At the beginning of the year, there could be ups and downs in your career, and you'll need to work hard to achieve good results. However, this year, you may take your career more seriously and work hard to strengthen your position. Your entire focus will be on your career and work, but you may have to wait for success. During this time, you'll need to work patiently and await the fruits of your labor.\n" +
                    "\n With the second phase of the year, your career may take a new turn. Your hard work could bear fruit at this time. Seniors will appreciate your work and dedication. Perhaps, during this time, you may achieve significant success in your career. If your work is related to employment, there may also be opportunities for promotion. Seniors will play a crucial role in your successful career. Their advice and insights could be vital for you. However, be cautious with your colleagues, as they may envy your success and conspire against you. So, be careful not to share your thoughts with them.",
            "In the coming year of 2024, your love life may see improved communication and compatibility in relationships. At the start of the year, there may not be significant changes in your love life. During this time, you could experience some disagreements with your love partner. Don't overemphasize these issues; instead, try to resolve them with your partner. Avoid putting pressure on your partner in any way, and don't let misunderstandings cloud your judgment.\n" +
                    "\n Avoid getting influenced by others' opinions, and don't doubt your partner. June and September could be positive months for your love life. During this time, your romantic relationship may strengthen. Your partner will value your feelings, and you may have opportunities to spend quality time together. You could go to the movies or have lunch together. For singles, there's a possibility of falling in love during this period.\n" +
                    "\n In the workplace, you may develop closer relationships with colleagues, or in college, a fellow student may develop special feelings for you. However, in May, exercise caution in matters of love. During this period, it's essential not to place blind trust in someone. For those who have recently started a new relationship, it may become more robust, and you can plan your future together.",
            "According to the Taurus horoscope for 2024, your health may be somewhat fragile this year, so you'll need to take your health more seriously. Pay special attention to your diet and consume a healthy diet. According to the predictions, you might face some old health issues this year. However, it's essential not to be negligent about your health because these ailments can be overcome.\n" +
                    "\n Regularly consult with a doctor for health check-ups, and if there are any minor issues, seek immediate treatment. You may feel fatigued this year, and stress could lead you in the direction of anxiety. Instead of overthinking any matter, take things slowly and steadily.\n" +
                    "\n In the early months of the year, your health will remain good, but during this period, you may experience issues like indigestion, fever, headaches, stomachaches, and indigestion. Have light meals at night and avoid spicy and fried food. Be cautious about the risk of eye infections during this time. On the other hand, November may not be particularly favorable for your health. However, towards the end of the year, you may experience health improvements.",
                    ""
    };

    public static String[] geminiYH = {
            "As per the predictions for 2024, this year looks promising for students of the Gemini zodiac sign. You may achieve good grades in your examinations during this year. Your determination towards your studies will remain strong, and your hard work and dedication will serve as a guiding light for your future. You will experience mental maturity this year, and your interest in education will be heightened.\n" +
                    "\n In the field of education, you may receive assistance from classmates and teachers, and your diligence could lead to success in major exams.\n" +
                    "\n For those students preparing for competitive exams, this year may bring a sense of accomplishment, but it will require diligent effort. Law students might find significant opportunities this year, but choosing reputable educational institutions will be crucial. Arts stream students should focus on professional courses. Opting for a prominent educational institution for higher studies could enhance your future prospects.",
            "Based on the outlook for 2024, it suggests that your married life may experience some normalcy this year, although you may have to face certain challenges. There could be some strain in your relationship with your partner, and disagreements may arise at times. It's important to promptly resolve any misunderstandings or doubts that may weaken your marital bonds due to misconceptions.\n" +
                    "\n Nevertheless, your married life is expected to remain content, and your relationship will improve as you understand each other's emotions. During this period, you might plan to go somewhere together and spend quality time in special places. Regardless of the circumstances, your partner will stand by your side, and their significant contribution to your endeavors will be vital.\n" +
                    "\n For children, this year holds the promise of improvement. Their performance in academics will be commendable, bringing smiles to your faces. The months of January, April, and October may offer favorable outcomes for children, but it's essential to pay attention to their health during this time and not neglect their activities. Considering education abroad might also be an option.",
            "Based on the basis of 2024, this year holds the potential for some significant financial developments for Gemini individuals. There are indications of financial gains for you, and new business ideas may help improve your financial status. This year, you may have a good opportunity to accumulate wealth. However, expanding your business might often require you to travel away from home. During this time, the possibility of foreign travel exists, which could bring you financial benefits through international connections. Nevertheless, it is advisable not to chase money to the extent that you neglect your personal life.\n" +
                    "\n Strive to maintain a balance between your professional and personal life. In the beginning of the year, your financial situation may strengthen, and your social status could also improve. Furthermore, towards the end of the year, you may come across several opportunities for financial growth in your career. If you are employed, there is potential for an increase in your income, and you might receive a significant reward from a company or organization. While circumstances may not always remain as they were, there might be moments when you feel financial disappointment. However, you should not get disheartened but rather wait for the right time to move forward. Maintain a balance between your earnings and expenses.",
            "This year is set to be very significant for entrepreneurs, and you are likely to benefit from it. Profitable opportunities may arise, and there is a chance for partnerships. You could potentially acquire wealth from various sources. Occasionally, conflicts and disputes may occur, but there is no need to panic. Maintain patience, and everything will be fine.\n" +
                    "\n For lawyers and legal experts, this year is very promising. If you are in the fields of medicine, education, or management, or have investments in these areas, you can expect good earnings.",
            "According to the horoscope for 2024, this year may appear average for your career, but it could turn out well if you put in the effort. It's essential to focus entirely on your work. To advance in your career, you will need to generate new ideas, and the advice of senior authorities could also be beneficial.\n" +
                    "\n Avoid choosing any shortcuts, as they might provide immediate gains but won't earn you long-term recognition in your work. Work diligently and stay away from office or workplace disputes as much as possible. During April-May, there's a possibility of a promotion, and seniors might commend your work. During this time, you may also receive a job offer from another reputable organization. Your career graph will rise, and there's a chance of an increase in your salary.\n" +
                    "\n Don't let success inflate your ego, and maintain discipline when it comes to hunger for success. Instead of being disheartened by failures in your career, keep working hard.",
            "According to the 2024 horoscope, this year suggests special significance for your love life. You can enjoy spending time with your loved ones and strengthen your relationships. In the beginning of the year, you will be on the lookout for an opportunity to share your feelings with your loved one. You might consider taking your relationship to a new level, and during the month of April, there could be efforts to further strengthen your bonds of love.\n" +
                    "\n If there's a specific issue causing disagreement, try to calmly address it. The month of April is crucial for making your relationships stronger. Around July, some passionate thoughts may arise, but handle them with care. In matters of love, there might be resistance from family members, but after dedicating time to your relationship, they might also provide support.",
            "According to the 2024 horoscope, this year will bring you health-related benefits, but at times, you may have to deal with minor health issues. In January, you may need to pay special attention to your health, such as skin-related problems like rashes and itching. Consulting a dermatologist for skin care advice is recommended. The period from March to November will be favorable for your health, and you will succeed in staying fit, although occasional health issues may arise for minor reasons. During this time, it's essential to focus on your well-being.\n" +
                    "\n Maintaining the right mental health with suitable recreational activities is also crucial. Consider joining a yoga club or gym to keep yourself physically fit. However, the most important thing is to maintain a healthy daily routine, including getting enough sleep and waking up on time. December might pose some health risks, and you may experience cold and flu symptoms, so it's essential to be mindful of your health and take proper care during that period.",
                    ""
    };

    public static String[] cancerYH = {
            "According to the Cancer horoscope for 2024, this year will be extremely auspicious for students. Especially for those students who are eager to learn new things and acquire knowledge, success will be on their side. This year, you will be highly dedicated to your studies and work diligently towards achieving your goals.\n" +
                    "\n The months of August to September will be particularly favorable for students. Those preparing for competitive exams in fields like civil services, engineering, medical, and management may achieve significant success during this period. Therefore, keep up your efforts and continue to work hard for excellent results.\n" +
                    "\n For students aspiring to pursue higher education abroad, there is a possibility of gaining admission to some of the world's leading educational institutions this year. This could be a crucial opportunity for your career.\n" +
                    "\n In 2024, you can also make significant efforts in the field of vocational education. However, between June and July, students preparing for MBAs may face some challenges. Therefore, it's essential to stay focused on your studies and concentrate on your preparations.\n" +
                    "\n During exam days, try to keep stress levels low and maintain a fresh mindset. Astrological indications suggest that the year 2024 will bring several favorable opportunities for Cancer students.",
            "According to the Cancer horoscope for 2024, the marital life of Cancer individuals will be filled with ups and downs this year. There may be some disagreements within the home, but regardless of the circumstances, they will be in your favor. In 2024, it's essential to avoid any misunderstandings and resolve all matters with your spouse through communication. Maintain complete trust in your life partner and offer them full support.\n" +
                    "\n This year, there may be health issues for your spouse, so pay special attention to their well-being. Those couples who have been anticipating the arrival of their first child might receive good news this year. On the other hand, unmarried natives might tie the knot this year. If you are considering a love marriage, have open discussions with your parents, as they may support your wishes.\n" +
                    "\n If your concerns involve your children, be prepared for potential changes in their behavior and the possibility of them becoming stubborn around the middle of the year. During this time, it might be necessary to communicate with them lovingly. Between June and September, pay particular attention to your children's health, as they may encounter infections and seasonal illnesses during this period. This year, do not overlook your children's health, as it could lead to significant problems if not addressed promptly.",
            "According to the 2024 horoscope, Cancer individuals can expect favorable financial outcomes this year. Specifically, this year holds good prospects for you. During this period, you will see an increase in income and wealth through various means. Financial improvements and a strengthened economic situation will enhance your social standing. During this time, your relationships and friendships will also grow stronger, and they will provide you with advice on financial matters.\n" +
                    "\n However, it's essential to be cautious about your financial affairs during this period, as there is also a possibility of financial losses, so you should avoid reckless behavior. If you are in business, your business might expand this year, leading to financial gains. Expenses may increase slightly in the middle of the year, but don't worry, as your income will also grow. It's important to plan your investments carefully during this time. If you're involved in the stock market, refrain from making impulsive decisions in financial transactions.\n" +
                    "\n Although there may be some ups and downs, circumstances will eventually be in your favor again. Overall, 2024 is a financially successful year for you, and you will accumulate more wealth while making progress in your career and business, enhancing your social status.",
            "According to the 2024 horoscope, in the field of business, this year indicates profitability. Business individuals are likely to succeed in earning more profits this year. If you have your own business, you may achieve recognition and success in that field. If you are considering a significant loan, you are likely to be successful, and you can invest this loan in your business. Competition in your business may be active, but there is no need to fear. It's important to let go of your pride and anger and engage in cooperation.",
            "According to the 2024 horoscope, for Cancer zodiac individuals, this year is looking quite favorable in terms of their career. There's a strong possibility of reaping the rewards of your hard work this year, so keep your efforts going and move forward. The months of February to March and November to December could be particularly significant for your career. During this period, you may hear good news related to your job or business. Job professionals may expect promotions and salary increments, while those seeking employment may secure jobs around September, October, and December. Additionally, this year holds the potential for success and achievements in the business sector. After March, businesspersons can expand their enterprises and make investments in various ventures, leading to positive outcomes.\n" +
                    "\n For job and business-related individuals, it's essential to avoid getting involved in any kind of disputes this year. Try to resolve issues and conflicts through communication peacefully. Between April and July, exercise extra caution in the career aspect. During this period, refrain from making hasty decisions or acting out of anger. Job professionals should avoid quitting their jobs hastily, as it might lead to a waiting period for another job. Business owners should exercise caution when considering investments without careful evaluation.",
            "According to the 2024 horoscope, this year promises to be memorable for your love life if you belong to the Cancer zodiac sign. You'll be taking another step forward in your love life and strengthening your relationship even further. As a result, your bond with your loved one will become stronger than ever before, and mutual trust and harmony will increase.\n" +
                    "\n As per the guidance of the stars, this year will bring you closer to your beloved. During this time, you will understand your partner's feelings and give importance to their thoughts. This year is expected to be very good for romantic affairs. However, it's important to note that during this period, you should avoid imposing your thoughts on your loved one, as it could lead to tension in your love life. If such a situation arises, be patient and try to reconcile through communication.\n" +
                    "\n In 2024, you may have several encounters with your loved one on social networking sites. During this time, you'll share your innermost feelings with each other. Be a bit sensitive during this period, as your private matters could become known to others. If you are employed, you might even develop a romantic relationship with a colleague. However, be cautious about revealing your relationship in the workplace to avoid unnecessary gossip.\n" +
                    "\n Similarly, if you are a college student, your heart may skip a beat for a classmate. Although this love might be one-sided initially, your partner is likely to reciprocate their feelings after some time has passed.",
            "In 2024, your health may be a bit delicate. During this period, you might experience some stress, possibly due to work or other matters. Additional stress can arise due to concerns about work or conflicts at home, so it's better to focus on getting your tasks done efficiently rather than overthinking them. Try not to escalate conflicts at work or at home, as it could lead to increased mental stress and anxiety.\n" +
                    "\n This year, there is a possibility of traveling, so it's advisable to wear comfortable clothing and have light meals during the journey to ensure a hassle-free experience. Between July and September, you may be susceptible to headaches, fever, and seasonal illnesses affecting your health. Additionally, insomnia could be a problem. To avoid these issues, maintain a balanced diet, follow a regular daily routine, and stay hydrated, as drinking plenty of water is the best way to keep your body healthy.\n" +
                    "\n If you have a history of pre-existing health conditions, your discomfort may increase this year. In case of any discomfort or pain, consult a doctor immediately. Rainy weather may lead to joint pain problems, so regular exercise and joint massages can help. Furthermore, to prevent digestive issues, adopt a balanced diet.",
                    ""
    };

    public static String[] leoYH = {
            "According to the horoscope for 2024, this year might be a bit challenging for students of Leo zodiac sign. You may face some difficulties in your studies, and your focus on academics may waver. However, for students preparing for competitive exams, this year could turn out to be quite favorable. If you have any upcoming exams this year, you may succeed in them. Your success in exams could depend heavily on your dedication and prayers to the divine.\n" +
                    "\n During this time, you might also explore the study of religious literature, and those students who have pursued language-related courses might benefit from their studies this year. Technical education may pique your interest, and you can consider enrolling in a computer course.\n" +
                    "\n Success in board exams will require hard work and diligent study, so students should be prepared to put in extra effort to climb the ladder of success. Meanwhile, students contemplating studying abroad should look to the months of April and May as a favorable time for such endeavors. Higher education could start off on a positive note, but you may encounter challenges later on. However, September and November hold the promise of good results for you.",
            "This year, there is a possibility of some minor disputes in your married life, but overall, it can be better than usual for you. Your relationship with your spouse will not only be strong but also compromises may be made between you. Financial assistance from your spouse is also possible, and they may be part of a significant achievement. If your spouse is working, there is a possibility of promotion or an increase in their salary.\n" +
                    "\n At the beginning of the year, your partner's health may face some issues, and you may encounter some challenges until March. There might be a slight change in your child's behavior, and disagreements over small matters are possible. During this time, you will need to communicate with them like friends and try to fulfill their reasonable demands. If that is not possible, then make them aware of the situation.\n" +
                    "\n You can propose spending quality time with your partner, such as going out for a movie or a dinner date. In the latter part of the year, happiness can prevail in your married life, and your spouse will appreciate your feelings. Their companionship and support will be with you every step of the way. Do not break their trust and give them the time they deserve.",
            "According to the horoscope for 2024, you may face some minor financial challenges in the coming year. However, despite this, you can also expect some positive outcomes in your financial life. Your financial situation will remain strong, although there may be some minor financial losses. By exercising caution in financial matters, you can navigate this situation successfully.\n" +
                    "\n During April and May, there are favorable financial indications for you. Your income may increase, and your business could also yield profits. You will be busy preparing for your upcoming financial plans. This year, there is a strong possibility of financial gains. Consider this year as an opportunity to accumulate wealth successfully.\n" +
                    "\n On the other hand, in February and March, your expenses may rise, and a significant portion of your wealth could be spent on various things. However, you have the ability to manage your financial situation effectively. If there is a pending property-related court case, the judgment may be in your favor. Financial benefits from foreign connections are possible, and you may even be able to pay off your old debts. If you have applied for a loan from a bank, it may get approved.",
            "In terms of business, this year will be favorable for you. All your desires will be fulfilled. It is a highly suitable time for electronic markets, and you can invest in them. You can also consider stock trading, but please note that the influence of Saturn may affect your stock investments, and you will benefit from long-term investments rather than short-term ones. In the business sector, if you are working in a partnership, you need to remain cautious, as otherwise, there may be difficulties and losses in the partnership.",
            "This year, you will need to work hard to achieve success in your career. You will find success in your career, but you may not be entirely satisfied with the results. Your hard work in the professional field can lead to a new recognition. There may also be an opportunity to work in a new place. The beginning of the year will bring better results in your career. Your dedication and commitment to your work will inspire your seniors. Your excellent work will be appreciated. During this time, you may have the opportunity for a promotion or an increase in your salary. It will be a better year for your career. However, you may need to be cautious. During this period, try to avoid getting involved in any kind of disputes, as your previous hard work could go to waste. Signs are pointing towards good results once again. You might feel dissatisfied with your success. During this time, conflicts may arise with your colleagues. Additionally, there is a possibility of conspiracies against you in the company, so it will be important to remain vigilant.",
            "According to the horoscope for 2024, your love life will be challenging this year, so you will need to be more cautious. There could be disagreements or misunderstandings in your romantic relationships. At times, you may appear dissatisfied with your relationships. During this period, try not to suppress any feelings. If there is any tension with your partner, make an effort to resolve it through open communication rather than reacting with anger. Instead of imposing your views on them, try to understand your partner's feelings. If your partner is upset with you, you can try to make amends by giving them a thoughtful gift. Love life won't always be difficult, as there will be many opportunities for you to enjoy romantic moments with your loved one. You may also have the chance to go on trips together, which will strengthen your relationship. Maintain trust with your partner. This year, you may even tie the knot with your life partner. Avoid rushing into new relationships and keep control of your emotions.",
            "According to the horoscope for 2024, your health will be quite good this year. In the early months of the year, you may face issues like colds and coughs. You might experience physical fatigue and a lack of energy. However, improvements in your health will start around mid-February. Overall, your health will be quite good throughout the year.\n" +
                    "\n During this time, you will be more serious about your health. Following a healthy daily routine will prove beneficial for you. Yoga and exercises will enhance your mental well-being and provide you with tranquility. You may encounter issues such as stomachaches, indigestion, headaches, and coughs during this period. It is essential not to ignore minor illnesses and seek immediate treatment.\n" +
                    "\n To maintain good health, it's crucial to adopt healthy habits. Stay away from smoking and alcohol, and follow a vegetarian diet. Engage in yoga and exercise daily. Pay attention to your mental peace.\n" +
                    "\n This year, you might face work-related stress, so make sure to allocate time for relaxation. Besides, you may encounter health issues related to the eyes, apart from fever and arthritis. Stay vigilant about your health and practice proper care.",
                    ""
    };

    //"शिक्षा","विवाह","फाइनेंस","व्यापार","करियर","प्रेम","स्वास्थ्य"

    public static String[] virgoYH = {
            "This year, students will be inclined to understand complex subjects and engage in reading religious scriptures. Your hidden talents might also come to the forefront this year, whether in sports or the arts. You will take your studies more seriously, and your hard work will shine through in your exam results. If your dedication to education remains strong, you are likely to succeed in every upcoming examination. There is also the possibility of pursuing higher education abroad.\n" +
                    "\n For students preparing for competitive exams, this year will require intense effort, and the competition may be tougher. However, with your hard work, you will be able to adapt to the challenges. Classmates can be of assistance, and the blessings of your teachers will continue to favor you. Engineering students may face some difficulties in their studies, and if you are conducting research in a particular subject, this period can be highly beneficial for you. Due to some health issues, you might feel less motivated to study during this period, but you will still perform well in your studies.",
            "According to the 2024 horoscope, this year may bring mixed effects to your married life. At the beginning of the year, there could be some health issues concerning your spouse. Challenges may arise in your marital life, but you can navigate them with understanding and maturity. Your marital bond could strengthen, and if your spouse is working, their hard work will bear fruit. During this period, it might be possible that your spouse cannot devote enough time to you, but you will need to manage these situations wisely. You should allocate some time for your spouse. \n" +
                    "\n Until March, your child's behavior may be somewhat erratic. They could be easily irritated over trivial matters and might exhibit stubbornness. There could also be some health concerns for them, so it's essential to take care of their well-being. However, improvements in their behavior might be observed later in the year.\n" +
                    "\n For newlyweds, there's a strong possibility of good news related to children this year. There's a significant chance of gaining some benefits from your spouse's side.",
            "According to the 2024 horoscope, this year, your financial life could appear better than usual, and you might sense this improvement right from the beginning of the year. You may receive income from various sources, although there is a possibility of increased expenses during this time. However, your circumstances will remain within your control. Primarily, there's a promise of financial gains for you. There is a strong chance of sudden financial gains during this period. Your ancestral property may see growth. If you invest in the stock market, this could be a profitable time for you. Beware of potential financial losses in August and September, even though your income remains stable. Meeting the educational and other needs of your children may entail extra expenses, so you'll need to spend your money thoughtfully during this time. In 2024, if the need arises, you can also borrow money from someone. The upcoming period looks good for your financial life. It's a favorable time for making investments in property, purchasing a new vehicle, or spending on the maintenance of an existing one.",
            "In the new year, you are likely to see profits in the business sector. There may be some travel involved in your business affairs. If you are involved in a partnership in your business, exercise caution. Your income will increase, and expenses will remain under control. The beginning of 2024 looks promising. From a business and financial perspective, this year should be favorable for you, so you should work hard. Individuals in journalism and electronic media-related fields will benefit this year. Expansion in your work is possible from the month of October. There may be minor challenges in life, but with a positive mindset, everything will be fine.",
            "This year, you may experience mixed results in your career. There will be several opportunities in this field, some of which may lead to disappointment, while others might bring you the taste of success. Your effective communication style can help you advance in your career. It is indicating positive outcomes in the professional sector for you. This year signals potential career growth. You might achieve successful results in your workplace, and your work may be appreciated by your company or organization. You could also receive rewards and a possible increase in your salary. However, there is a possibility of changing jobs or transferring. On the other hand, individuals involved in business can also expect success and financial gains this year. You will need to focus wholeheartedly on your work. Ignore unnecessary office gossip and avoid getting involved in any disputes. This will help you build a positive image as an employee and benefit you. Remember, if the outcomes are not as expected, try to work harder instead of being disheartened. Stay patient and move forward with a positive mindset.",
            "In 2024, you may experience mixed weather in your love life, with both ups and downs possible. The beginning of the year might not seem particularly exceptional in terms of your love life, although improvements could be seen later on. Avoid showing anger in communication and make efforts to steer your love in the right direction. Give importance to your partner in your relationship and try to understand their perspectives. For those already in relationships, your love bonds may become stronger. Your relationship will stay healthy. The period from January to March could bring some turbulence to your love life, and during this time, you may even consider parting ways. So, avoid arguments with your partner. If there are disputes in your relationship, try to reach a compromise. June and December may be favorable times for love relationships. During this period, someone might touch your heart, and you could even start new relationships. However, don't rush into things in matters of the heart; instead, approach them with thoughtful consideration, even in the early stages of new relationships.",
            "According to the 2024 horoscope, this year will bring fluctuations in your health. You will experience mixed results in the health department. You can expect to see improvements in your well-being, but there may also be some health issues. At the beginning of the year, you may appear as an enthusiastic and energetic individual, but this period might not be the best for your health, and there could be some health setbacks. Be cautious of illnesses related to weather changes during this time.\n" +
                    "\n Furthermore, you might also experience a burden of work in your context, but you will handle it with your capabilities. Be mindful of diseases associated with changing weather conditions. It's essential to maintain a regular exercise routine, get adequate sleep, and take proper care of your body, especially during this period.\n" +
                    "\n May, August, and September are expected to be good months for your health. Incorporating yoga and meditation into your daily routine can improve your mental health and give your skin a radiant glow. Following a healthy daily routine and avoiding excessive consumption of meat and alcohol would be beneficial.",
                    ""
    };

    public static String[] libraYH = {
            "According to your horoscope for 2024, this year holds special significance for students. Diligence and dedication to your studies will be of utmost importance. Good prospects for success in examinations are on the horizon. This year, students have the potential to gain practical knowledge alongside bookish knowledge. Those preparing for competitive exams may find excellent opportunities for success. Education is highly favored this year, so you should make full use of it.\n" +
                    "\n You should remain enthusiastic about your studies and academic subjects right from the beginning of the year. There might be increased positive competition among students in schools and colleges. Your classmates can assist you, and your hard work will catch the attention of teachers. The results of upcoming exams could align with your expectations. For students considering higher education abroad, this could be a golden opportunity, meaning you might be able to study overseas. Medical and engineering students may need to put in extra effort. Admission to reputable institutions in these fields could be challenging.Students preparing for civil services exams may also need to work harder because the competition level could be significantly high this year.",
            "In the beginning of the year 2024, your marital life may experience some stress. There could be indications of ups and downs in your marital life during this period. It's advisable to make an effort to spend quality time with your spouse and overlook their minor mistakes. Additionally, it's better not to harbor any resentment towards them during this phase. Patience should also be introduced into your relationship. Improvements in circumstances are possible, and compromises may be reached in your married life.\n" +
                    "\n You could build a better understanding between you and your spouse during this time. They will not only comprehend your feelings but also appreciate you. The marital life may be somewhat challenging during this period, so you'll need to be cautious. Your children's health will remain good, and they will be more energetic. They are likely to perform better in their studies. Responsible behavior in their conduct will be observed.\n" +
                    "\n In August, children may face some difficulties, so be attentive to their needs during this time. If they are being stubborn about something, try to explain to them with love, and instead of behaving like parents, treat them more like friends. This year, you can plan trips with your spouse and children. This will foster unity, love, and harmony among you all, and it will help resolve any differences.",
            "According to the 2024 horoscope, it appears to be a year filled with hope and promise for individuals born under the Libra zodiac sign. Financially, you can expect better results in the economic sector. Fate will favor you in this domain, and you'll encounter several opportunities to strengthen your financial position. There's a strong likelihood of financial gains this year, particularly in May, August, and December. During this time, the chances of experiencing financial benefits are high.\n" +
                    "\n Furthermore, you might witness a significant profit by mid-year, but caution is advised beyond July. Avoid making major financial decisions or investments during this time. There may be unexpected increases in your expenses, so be mindful. Try not to spend money on unnecessary items. Similar circumstances might be seen in November, so exercise financial prudence during this period.\n" +
                    "\n This year, there is a strong possibility of an increase in your ancestral property. Family members will be supportive in financial matters. You might also consider purchasing a new vehicle this year. There are strong indications of benefiting from foreign connections. The business sector holds potential for increased profits.",
            "You may have an opportunity to start a new business venture. There could be a chance to engage in a partnership in business. If you're interested in launching a factory, this time could be favorable for you, but it will require hard work, and you're likely to reap benefits.\n" +
                    "\n Selling off old property might enable you to purchase new assets. Your profit may not meet your expectations, but there's no need to be disheartened. You have the capability to accomplish anything. Avoid sudden investments; instead, plan your expenses and seek advice from a trusted financial advisor before spending.\n" +
                    "\n You can consider taking a loan from a bank or a partner for investment in a business venture. There's a likelihood of expenses related to auspicious activities. This year, you can work in a partnership.",
            "In 2024, your career is likely to yield quite positive results. After March, your new ideas will lead you towards success. During this time, you can expect better outcomes in your professional field. You will receive support from your colleagues, though perhaps not to the extent you might expect, so avoid depending entirely on them.\n" +
                    "\n There's a possibility of receiving significant career news during this period. You could potentially get a job promotion or an increase in your income. Your communication style will play a crucial role in advancing your career. You'll excel in explaining things to others, leading to favorable results.\n" +
                    "\n If you're working in the government sector, your results will be even more successful, and if you're in the private sector, you can still achieve good outcomes, although it may require considerable effort. If you're searching for a job, there's a likelihood of finding one. Furthermore, you may have opportunities for travel due to your job.For those in the IT sector, 2024 holds new hopes and possibilities.",
            "This year, you can expect favorable outcomes in your love life. The year 2024 might be an excellent year for your love life. You may start new relationships during this year. Your compatibility with your love partner will also improve. You can even go on trips together and enjoy quality time.\n" +
                    "\n However, there might be situations that could leave you feeling disappointed, so be mindful of that. You might also encounter some stress; pay attention to it. Avoid putting any pressure on your love partner. If you need to discuss something with them, communicate directly and avoid beating around the bush.\n" +
                    "\n For those seeking love, this year signals the possibility of finding true love. If a new relationship is forming, don't rush into it. First, establish trust with your partner and then work on nurturing the relationship.\n" +
                    "\n In 2024, your romantic relationship could also transform into a marital one. This may require obtaining approval from your family, and you'll need to be okay with that. Avoid doubts and misunderstandings in your love relationships and maintain trust with your beloved.",
            "This year, there is a possibility of good days ahead for your health. In 2024, not only will you experience improvements in your health, but you may also find relief from pre-existing ailments. You will take your health seriously, and as a result, you can consider engaging in activities like sports, running, yoga, and joining a gym to stay fit.\n" +
                    "\n Although you might face some mental stress in January, this situation will be temporary, and you will experience mental satisfaction. Due to good health, you will work harder in your professional life. You will exhibit enthusiasm in handling tasks.\n" +
                    "\n If you happen to fall ill during this period, you will recover quickly. Your mind will remain content, and you will foster positive thoughts that will help you progress.\n" +
                    "\n To maintain good health, adopt a healthy lifestyle with special attention to your diet. Avoid consuming excessive oily foods, and if you are fond of fast food, exercise restraint. You may experience a slight increase in your weight, so stay vigilant.\n" +
                    "\n Moreover, you might face some skin-related issues, but if you seek timely treatment, these problems will be resolved quickly. There could be a possibility of cough and cold issues in November-December, so also take care of your health during this time.",
                    ""
    };
    //"शिक्षा","विवाह","फाइनेंस","व्यापार","करियर","प्रेम","स्वास्थ्य"
    public static String[] scorpiusYH = {
            "According to the Scorpio horoscope for 2024, this year could prove to be quite favorable for Scorpio students. You may achieve good results in your studies during this year. You will work hard to succeed in your educational pursuits, and your efforts are likely to yield positive outcomes. Your teachers will appreciate your dedication and be ready to assist you in every possible way. The educational environment will be conducive to your progress, making studying more effective.\n" +
                    "\n If you plan to appear for any competitive exams during this time, success may be on the horizon. To achieve better results in your studies, you will need to enhance your efforts further. If you are a boarding school student, the examination results are likely to be in your favor. Alongside your studies, allocate some time to nurture your talents. In your free time, you may consider taking courses or diplomas aligned with your interests.\n" +
                    "\n For those pursuing courses in fields related to knowledge, there may be excellent opportunities. Tourism and management sectors will offer several possibilities for students. To achieve your goals, you'll need to maintain focus and dedication. If you have any health issues or ailments, you should pay special attention to them and adopt measures to address and overcome them.",
            "According to the Scorpio horoscope for 2024, your married life will remain normal this year. However, there may be small disagreements with your life partner. Despite this, your love for each other will grow. You will both find love and support in each other. Resolve misunderstandings promptly to prevent them from escalating.There might be some health issues with your spouse, which could be a cause for concern. Instead of worrying, you can support them and show empathy towards their health. \n" +
                    "\n You will receive respect from your children, and they will be attracted to you. You will be ready to spend time with your children and encourage them to progress in their professional fields. Your children will also perform well in their educational pursuits.At work, you should make an effort to give time to your family, although work commitments may sometimes affect your married life. Handle this carefully with satisfaction. Avoid arguments with your partner, understand their feelings, and try to fulfill their needs.",
            "Based on the year 2024, Scorpio individuals may receive mixed signals in their financial life. There could be fluctuations in their financial situation, with disparities between their expenses and income. In other words, expenses might increase this year, but their income may remain stable. In this scenario, it will be essential for them to manage their expenditures carefully to maintain a balance between income and expenses. They can consider investing their funds in entertainment and luxury items, potentially resulting in financial gains. During this time, they might achieve success in wealth accumulation, with the possibility of unexpected financial gains in September. If there is a pending legal matter related to assets, the verdict may turn in their favor.\n" +
                    "\n Despite the inflow of finances, it's crucial to contemplate how to ethically utilize this wealth. Avoid getting tempted by unethical or illegal activities. In 2024, they may even consider borrowing money from someone to overcome their financial emergencies, cut down on luxury purchases, and focus on saving. Be cautious about potential property-related disputes and stay vigilant.",
            "From a business perspective, the outcome of this year may be mixed. You can hope for significant profits, but they might also fall short of your expectations. Utilizing unethical sources for profit is an option, but it's not advisable. Please make an honest effort to earn profits, as this can also benefit you. Your luck in business this year could help you achieve your goals, with the support of friends and loved ones. However, there may be challenges on some days during the year. If you are working in a partnership, exercise caution, as there is a possibility of deceit.",
            "Based on the year 2024, Scorpio individuals may have the possibility of improvement in their careers. The prospects appear promising for both jobs and businesses. During this time, you will put in hard work to advance your career. There could be several golden opportunities ahead of you. Due to your excellent performance, you may receive a job offer from a reputable organization. There are also possibilities of exploring opportunities abroad in your career field. If you seize these opportunities in time, they could lead to significant success for you this year. You might achieve career milestones this year, and there's potential for promotions or an increase in your income. Favorable outcomes are expected in your career field during this time, and you'll receive full support from seniors. Your work and ideas will be appreciated.\n" +
                    "\n During this time, try not to become overly dependent on colleagues, and it's better if they don't envy your success or try to claim credit for your achievements. Stay alert, especially at the beginning of the year, as there might be a chance of a job transfer. Avoid unnecessary conflicts at the office or workplace and focus on your work with complete honesty. Follow the guidance of seniors and complete your tasks on time.",
            "Based on the year 2024, it looks like a good year for love relationships. You will have opportunities for romance with your dear partner, and your relationship will strengthen. If you are unmarried, there is potential for a love marriage. You will share your feelings openly with your beloved, and there will be harmony between both of you. You can go on enjoyable trips together, including long drives and outings to the cinema. You can also have lunch and dinner dates together in February. Moreover, in April and May, you can expect positive developments.\n" +
                    "\n However, it's not an ideal time for love relationships. Misunderstandings during this period could strain your relationship. Avoid putting any pressure on your partner, and refrain from baseless suspicions. Small arguments may occur during this time, but if you communicate openly, the outcomes will be better. If there is an ongoing dispute in your relationship, try to resolve it peacefully. If you're considering a new relationship, don't rush into making any decisions.",
            "In accordance with 2024, Scorpio individuals will need to pay special attention to their health this year. Neglecting your health can come at a high cost. It's essential to incorporate physical exercises into your daily routine, such as yoga, workouts, meditation, running, morning walks, and gym sessions, to maintain your fitness. Avoid laziness and aim to get adequate sleep at night and wake up early in the morning. Pay attention to your diet and eat mindfully. Remember, your health is your greatest asset. It's crucial to prioritize your health right from the beginning of the year.\n" +
                    "\n According to the year 2024, Scorpio individuals may encounter some health issues. During this time, you might experience certain health concerns. However, after April, there could be improvements in your health, and you may find relief. Nevertheless, in May and June, you might face some physical discomfort, and your health condition could become delicate. You may be prone to conditions like fever, cold, cough, swelling, and other health problems during this period. Your immune system may be weakened, so consult a doctor in advance and take care of your health.",
                    ""
    };
    public static String[] sagittariusYH = {
            "According to the annual Sagittarius horoscope for 2024, this year appears to be ordinary for students. If students work hard, they can make this year better than average. During exams, you may encounter some challenges in your studies. During this time, you will need to pay special attention to your studies, as otherwise, it can affect your academic performance. Maintain focus on your studies. Understanding your subjects may pose some difficulties, so seek help from teachers and classmates.\n" +
                    "\n For students in technical fields, this year might be a bit challenging, requiring them to put in extra effort to achieve success. Arts stream students should focus on studying good literature to enhance their knowledge. Some students aiming for higher education may face certain challenges, but with your efforts, you can overcome these issues successfully. Take care of your health and stay focused on your goals.",
            "In 2024, indications for married life are suggesting occasional ups and downs. This year, you may face changing circumstances in your marital life. If any misunderstandings or conflicts arise, make an effort to understand them and show dedication and support towards your spouse. Resolve any misunderstandings promptly; otherwise, the situation may become more challenging. Try to understand your partner's needs and fulfill their responsibilities, which can lead to a happy married life.\n" +
                    "\n This year, your children are likely to enjoy a peaceful and joyful life, and the horoscope indicates happiness related to offspring. They will mature and perform well in their educational endeavors. However, pay special attention to their health in the months of June and August, as they may encounter some health issues.\n" +
                    "\n For married couples, do not shy away from the responsibilities of married life and avoid showing indifference towards your spouse, as it can be helpful in reaching a content and blissful married life. If you are unmarried, you may consider entering the bonds of matrimony this year.",
            "According to the 2024 Sagittarius horoscope, this year holds special promise for your financial aspect. There are indications of financial growth, but you will need to work hard to make the most of it, which could result in doubling your gains. Keep a close eye on your expenses, as this will help control unnecessary expenditures and save money. You will experience financial benefits, and the economic conditions will favor you during this time. You might receive financial assistance from various sources, and there will be an increase in ancestral property.\n" +
                    "\n If you are involved in business or entrepreneurship, you could achieve financial gains, and there is a possibility of expansion in your business. Your significant financial decisions may lead to significant success, and if you plan to make substantial investments, you can seek advice from experienced individuals.With your financial situation becoming robust, you may consider purchasing new vehicles or other valuable assets. This year, your spending may be directed towards the purchase of electronic goods, which could prove to be a worthwhile investment for you. You might also experience financial gains in the stock market, and there is a chance of success in a lottery for you this year.",
            "From a business perspective, this year could offer you opportunities for better profits. However, making hasty decisions would not be advisable. It is essential to exercise caution and make decisions only after carefully considering the right and wrong. When making any business decisions, you must remain extremely vigilant; otherwise, you may incur losses.\n" +
                    "\n This year, you may have intentions of earning money, but please avoid any illegal means. Engaging in such practices can lead to negative consequences rather than positive outcomes. You could find yourself trapped in a situation that is challenging to escape from. Therefore, maintaining complete transparency in financial matters is the key to resolving issues successfully.",
            "According to the 2024 Sagittarius horoscope, this year may bring a mixed bag of opportunities and challenges in your career. You may encounter ups and downs, but your career is poised for growth. You can expect favorable results at this time, and the possibility of a good job offer may arise. Senior colleagues will also support you, and your teamwork will be highly cooperative. Please ensure that you complete your work on time, as your hard work will bear fruit. You might see career advancement or an increase in your salary this year. However, it's crucial to handle pride with caution, as it could have consequences. Your competitors may resist your success, and there might be plots against you, so be mindful not to fall into their traps.\n" +
                    "\n Nevertheless, this year could also test you with situations that involve disappointment and bitter experiences. You may face adverse results in your career during such times. Fear may linger in your mind regarding your career. In such adverse situations, please focus on building your resilience and put in extra effort in your professional endeavors. With determination, no one can stop you from achieving success.",
            "According to the 2024 love horoscope for Sagittarius, this year is poised to be a good one for romantic relationships, although occasional disagreements with your beloved may arise. You will have several opportunities to strengthen your love life. If there are any disputes with your partner, it's advisable to resolve them through communication rather than escalating the issues. This year holds promising signs for your love life, with a deepening of your romantic bonds. For those starting new relationships, love is likely to flourish during this period. You'll be fully devoted to your beloved, and you'll enjoy moments of happiness together. There could be plans for entertainment, dinners, or lunches together. Furthermore, it's a fantastic time for romance. You'll celebrate special occasions like birthdays with thoughtful gifts and might even plan a grand party for your partner.\n" +
                    "\n However, at times, you might also face disappointments and setbacks in your love life. Your beloved could be upset or irritated with you on certain occasions. In such situations, your efforts should be focused on soothing and mending the relationship with love and care.",
            "According to the annual horoscope for Sagittarius in 2024, this year, the health of Sagittarius individuals will generally remain stable, but there might be occasional health-related challenges. The months of March and April indicate favorable times for your health. However, during this year, you may face issues like arthritis or back pain, so it's essential to take special care of your health. You may also encounter problems like cough, fever, headaches, swelling, and more. Strengthen your immune system to combat these issues effectively. Travel may lead to physical exhaustion, so only travel when necessary, and exercise caution while driving. Mental stress due to worries could have a negative impact on your health, so try to manage stress and not let it affect you. If you feel anger, strive to control it because dealing with anger could be a challenge this year. If you have diabetes, pay special attention to your diet. However, going on an adventurous trip could rejuvenate you. Alternatively, practicing yoga can significantly contribute to improving your health.",
            ""
    };
    //"शिक्षा","विवाह","फाइनेंस","व्यापार","करियर","प्रेम","स्वास्थ्य"
    public static String[] capricornusYH = {
            "Based on the foundation of the year 2024, students of the Capricorn sign will find this year to be filled with happiness. Success will be achieved through hard work in your studies, and you will obtain good results in your examinations. If you are preparing for a competitive exam, you will attain positive outcomes. Time will be on your side, so if you put in the effort, success is certainly within your grasp. You will show respect to your teachers, and your focus will remain on your studies.\n" +
                    "\n Students won't face many obstacles in obtaining higher education. You can secure admission in reputable institutions. If you wish to pursue education abroad, you will achieve success, but it's essential to thoroughly research the institution before applying. If you are a board class student, you will receive good results this year, although you will need rigorous training for the exams.\n" +
                    "\n Those preparing for medical entrance exams will need to put in a little extra effort, as the competition for medical entrance exams may be intense this year. Similarly, students in the field of engineering will need to work harder, so pay attention to your studies. This year, you will not only develop your knowledge but also enhance your talents alongside your studies.",
            "The year 2024 will be very good for your married life. There will be understanding and support between you and your spouse. In every situation, your spouse will stand by your side and be your companion. At the beginning of the year, there are no significant events foreseen in your marital life, but after March, the colors of happiness will shine bright.\n" +
                    "\n You may receive exceptional benefits from your spouse, and you might hear some good news from their end. They will understand your emotions and respect them. Avoid any actions that create distance between you. You will fulfill their needs.\n" +
                    "\n If you have children, this year will be good for them. Although they may face health-related issues, ensure you take care of their well-being during this time. You will prioritize the progress of your children. To fill your married life with happiness, provide your spouse with adequate time and support.",
            "Based on the year 2024, your financial life will experience mixed fortunes. There is a possibility of increased expenses this year, although the likelihood of income growth is low. You may gain financial benefits through international connections. At the start of the year, you will have opportunities to acquire wealth, and your sources of income will expand. However, you will need to manage your expenses wisely to strengthen your financial situation.\n" +
                    "\n Household expenditures may rise, and there might be pressure on your wallet when purchasing electronic items. Before making financial decisions, seek advice from experienced individuals in this regard, and then make your decisions. Property holdings will grow, but there may be some disputes in this regard. To avoid this, ensure that you do not escalate conflicts, as it could lead to legal complications.\n" +
                    "\n If you utilize your assets wisely, you will undoubtedly benefit financially. Avoid risky businesses, and if you invest in the stock market, exercise caution during this time. Remember, if you do not manage your finances prudently, you may have to deal with the burden of debt this year. ",
            "According to the Capricorn horoscope for 2024, this year won't bring any significant profits your way, but it will still hold some opportunities. You will put in a full effort to expand your business, although success may come a bit later. There could be improvements related to hospital-related matters. New partners may also emerge in your business, and you should take advantage of their benefits. In reality, the profit or loss for this year will depend on your efforts and how effectively you have utilized them.",
            "According to the Capricorn horoscope for 2024, this year brings positive indications for your career. Your professional life will shine brightly, with success in your job or business endeavors. Right from the beginning of the year, you will see favorable results in your career. Your hard work may yield excellent results. If you're employed, there's a chance for promotions or incentives from your company. Several good news pieces may be heading your way.\n" +
                    "\n There will be advancements in your business, and you may even have the opportunity for a relocation, with the company sending you to your preferred location. The possibility of going abroad is also on the cards. You will work skillfully in your field, and your efforts will benefit the company. Your plans may bring profits to the organization, and your position within the company may rise.\n" +
                    "\n You may take on a multitasking role this year and establish good relationships with colleagues and senior officials in the organization. Their support can propel you forward. On the other hand, be cautious when entering partnerships in business. Avoid placing excessive trust in your partners, and be sure to thoroughly read any documents before signing them.",
            "According to the Capricorn horoscope for 2024, this year promises a beautiful celebration of joy in your love life. Your love life will be full of excitement and romance. If you desire to make your partner your life companion, this year may bring that possibility to fruition. Your relationships will be strong, and the distance between you and your partner will decrease. You will not feel incomplete, and your bond will grow stronger.\n" +
                    "\n You both will spend quality time together and may even plan to attend a party or two. This year is a favorable time for your love life. Your partner will understand your emotions and support you. You will trust each other, and your relationship will deepen. You may have the opportunity to touch deeper emotional levels in your relationship this year.\n" +
                    "\n Although minor disagreements with your partner may occur, it's important to maintain trust in your love and avoid imposing conditions on it. Those longing for love will have a chance to find their true love. If you're forming new relationships, take your time in matters of love, and give your beloved the time they deserve. Especially in the beginning, keep control over your passionate thoughts. If there is any misunderstanding with your partner, resolve it promptly, or it could lead to cracks in the relationship.",
            "According to the Capricorn horoscope for 2024, this year, you will need to pay full attention to your health. In terms of health, this year is not particularly favorable. Your health will remain okay, but you may face some health-related issues. These issues may include eye problems, insomnia, joint pain, digestive problems, and more. This year, make an effort to stay fit by practicing yoga and exercise, and if you have any physical issues, consult a doctor promptly.\n" +
                    "\n You may feel weakness and experience fatigue during your daily activities. There could be a lack of energy in your body, and you might also feel mental stress. If you are suffering from any illness, it's essential to pay extra attention to your health at this time. If a doctor has advised you to restrict certain foods, follow their advice, and avoid items that could further harm your health. Pay attention to a healthy diet and steer clear of processed, fast food, and fried food. Ensure that you keep your body adequately hydrated by drinking enough water.",
                    ""
    };

    //"शिक्षा","विवाह","फाइनेंस","व्यापार","करियर","प्रेम","स्वास्थ्य"

    public static String[] aquariusYH = {
            "For students, this year will be a bit challenging. Good academic results will come to students only when they work hard. This means that your luck may be a bit less favorable this year, so you will have to rely entirely on your hard work. There is a possibility of going abroad for higher education. Students may find excellent opportunities for their studies during this time. Students should maintain focus on their studies. If for any reason your mind is disturbed or sad, address that issue, or it could affect your studies negatively.\n" +
                     "\n Keep good company with diligent students in school or college. If you are preparing for board exams, you will need to pay extra attention to your studies. Mathematics students may benefit, while science students may find practical aspects more interesting. Along with your studies, work on developing your talents. If you have any hidden talents, you can nurture them. This year holds a lot of potential for students pursuing professional studies. Your efforts should be focused on not letting any opportunity slip through your fingers.\"",
            "The year 2024 will be special for your marital life, although there may be some challenging situations. During this time, there may be some issues in your marital life. Instead of getting anxious about it, you will have to face these challenges. You may feel some dissatisfaction in your marital life at this time, and changes in your partner's behavior may leave you somewhat disappointed. During this time, you should make an effort to understand your partner's feelings rather than letting your emotions dictate your actions. Spending time with your spouse will make them feel that you are standing by them in every situation, which will improve your relationship.\n" +
                    "\n From May onwards, the circumstances for your marital life will be favorable. Your spouse will be completely dedicated to you. However, in November-December, your spouse may need you more. Try to avoid conflicts and avoid arguing with your spouse. If you have children, this year will be very good for them. There will be mental development in them, although after March, they may become a bit stubborn. In such a situation, treat them like a friend and provide them with information about situations with love.",
            "According to the Aquarius horoscope for 2024, this year could bring some significant changes to your financial life. You may have opportunities for financial gains, strengthening your financial position. You are likely to succeed in accumulating wealth this year. After March, there could be improvements in your financial situation, and you may have multiple sources of income, which will make your financial outlook appear promising. From a financial perspective, you can expect to have a very successful year.\n" +
                    "\n At the beginning of the year, there is a possibility of financial gains, and you may receive some good news related to financial benefits. If you are in business, there will be financial gains, and if you are employed, there is a possibility of an increase in your income. However, for those involved in agriculture, this year may be average, but hard work may lead to higher crop yields and financial profit. Siblings may also experience financial improvements, and there could be gains from ancestral property. You may be able to purchase a new vehicle or home this year. Towards the end of the year, circumstances will be more favorable, and if you have applied for a bank loan, you may be successful. Just remember to spend money wisely. Overall, this year seems promising for you from a financial perspective.",
            "Good results are expected in the context of business. Please be mindful not to engage in any unethical activities or interfere in someone else's work to avoid causing harm. This year, a new business venture may also begin, and you can achieve everything you desire if you continue your efforts. It's essential to remain more cautious in your business endeavors this year.",
            "According to the Aquarius annual horoscope for 2024, this year will bring favorable results for your career, potentially propelling you to new heights. You are likely to achieve success in your professional field, and your decisions will further enhance your career prospects. As a result of your good decisions, you can expect golden opportunities to arise.\n" +
                    "\n Your senior colleagues and co-workers will commend your work and decisions, so it's important not to let arrogance get the better of you. During this time, your colleagues will support your career, and together with them, you'll progress. If you are in business, partnerships can bring you benefits. The months of January, August, and December could be quite promising for you, while caution should be exercised in June and September. During this period, avoid getting involved in any disputes and maintain discipline in your workspace. After this phase, conditions will become more favorable again, and your career will regain its momentum. If you work in the public sector, this year will be beneficial for you. You will display higher satisfaction with your work, and the possibility of a transfer to a desired location is also on the cards, although it may require some effort on your part.",
            "According to the Aquarius horoscope for 2024, your love life will be better than usual this year. The year might start off a bit slow, and you may face ups and downs in your love life until March. However, during this period, have complete trust in your love and maintain faith in your relationship. Keep communicating with your partner and work to resolve any misconceptions or doubts that may arise in your mind.\n" +
                    "\n This year, you may embark on a long journey with your partner, possibly to a favorite destination like a hill station or a coastal area. The month of May will be auspicious for your love life, and there are indications of marriage in your romantic relationship. If you wish to transition your love relationship into a marital bond, this could be the best time for you. Spend quality time with your partner to rejuvenate your love and enjoy the bond and support in your relationship.\n" +
                    "\n However, if you plan to test your love in any way, do so with careful consideration, as there may be a fear of disrupting your relationship. Maintain transparency in your love and avoid hiding anything from your partner that could potentially become a source of conflict or mistrust in the future.",
            "According to the Aquarius horoscope for 2024, your health life will be good this year. You will remain healthy and feel more energetic. You'll exude enthusiasm, zeal, and incredible vitality. Your courage will increase, enabling you to excel in significant endeavors. However, at times, you may experience minor illnesses or weather-related ailments like fever, headaches, or insomnia. While these health issues won't harm you significantly, it's advisable to seek prompt medical attention in such cases.\n" +
                    "\n Mentally, you'll be content, and this positive mindset will have a beneficial impact on your health. Your personality will undergo refinement, and your charisma will attract people. Additionally, your communication style will improve. Your impressive communication skills will help you leave a mark on others positively.\n" +
                    "\n To maintain your well-being, steer clear of negative influences and stay away from wrongdoing. Be cautious while driving and avoid driving under the influence. This year, you can practice yoga, exercise, or visit the gym to keep yourself fit. Pay special attention to your diet and nutrition alongside physical exercise. Incorporating Surya Namaskar (Sun Salutation) into your routine will be beneficial for your physical fitness.",
                    ""
    };

    //"शिक्षा","विवाह","फाइनेंस","व्यापार","करियर","प्रेम","स्वास्थ्य"
    public static String[] piscesYH = {
            "If you are a student, you may achieve some kind of success in your studies this year, but pay special attention to your studies. Your focus may be disturbed for some reason, so stay alert. You will put your full effort into your exams, and this will yield positive results. If you are an engineering student, you can focus more on your projects. This year can also be important for students learning a foreign language or pursuing courses or diplomas related to a foreign language. Respect your teachers and become a self-disciplined student because discipline can lead to success in major exams. Along with the syllabus, also read books by renowned authors. Foster a friendship with literature in your student life. Those students preparing for a competition may face challenges, but the decision to work hard for success may be the right one. Cultivate your curiosity because being curious can propel you forward, otherwise, you may lag behind.",
            "If you are married, the year 2024 could be special for you. During this year, you may experience some very good moments in your married life. Your spouse could be the reason for your happiness. However, you may also have to face some challenges that could make you feel disappointed. To avoid such situations, it would be better for you to think about them. Give your husband enough time for his share of the responsibilities. Even though there might be conflicts due to pride or misunderstandings between you two, keep pride out of the relationship, and if there's any doubt or misunderstanding, resolve it immediately. This way, you will not have any problems in your married life. Your husband's health may be fragile, so take care of his health and don't let his morale break. If your husband is upset about something, don't let him repeat the same mistake. This will make you a understanding partner in front of your husband. Your child's health may decline, so take care of their health in March. These children may have a sense of understanding. The child will understand his responsibilities, and seeing this, you will also be happy. Fulfill the child's needs. If the child behaves stubbornly in any way, explain it lovingly. To make your married life happy, you will have to be dedicated to your married life.",
            "In the year 2024, you may have to deal with financial issues, so it's important to carefully assess your financial situation during this year. Before taking any risky steps, you should weigh your options because you could potentially incur financial losses. Your income will remain stable, but there is a possibility of increased expenses. During this time, you'll need to cut down on your expenditures to maintain a balance between your income and expenses. You might have the opportunity to acquire wealth during this period. However, there is also a chance of financial setbacks in August and November.\n" +
                    "\n During this time, it's advisable to stay away from the stock market and gambling markets. Additionally, exercise caution when it comes to trusting someone in financial matters and avoid displaying excessive sensitivity. If you are involved in business, there may be profits, but you could encounter some issues with your business partner that may not be favorable for the business. Be mindful to avoid legal disputes, as they could result in financial losses. While you may indulge in expensive purchases, it's important to control your expensive habits; otherwise, you could face financial problems.\n" +
                    "\n Your spouse's support may lead to financial gains for you.",
            "For individuals born under the Pisces sign, if they are involved in any business, this year could bring them better profits, but they will need to wait until October for this to materialize. After September, there is a possibility of progress in your business. New business relationships may develop, and you should take advantage of them. Until September, you might need to borrow money for your work and make investments in your business. This will be beneficial for your business in the long run.\n" +
                    "\n From a business perspective, the end of the year looks favorable for you, but making hasty decisions may not be advisable. There will be financial gains, but rushing into decisions may not be the right approach.",
            "According to the astrology horoscope for 2024, this year could shine brightly for your career as the circumstances seem favorable for your professional growth. If you stay mentally and physically healthy, your career could reach new heights this year. In your workplace, you may gain recognition, and your image may improve as a diligent, honest, and conscientious worker. There's also a possibility of job advancement and receiving positive news related to promotions. Be sure not to let your pride get the best of you. Your social standing could see an increase.\n" +
                    "\n This year may bring several opportunities your way. Be prepared to make the most of them. Cultivate an interest in technology as it could be valuable in your career. Your career path during this time may have its challenges, so keep yourself in full control. Avoid actions that could tarnish your reputation without valid reasons, and follow the guidance of your elders. If you're involved in business, there's a potential for success. Expansion in your business is possible, and you can present yourself as a successful entrepreneur without hesitating to take calculated risks. This year, you won't lack the courage and self-confidence needed to accomplish significant tasks.",
            "For matters of love and romance, this year could be a mixed bag. In this year, you may find yourself in some uncertainty in your love life. There could be some ambiguity in your relationship matters. At times, important discussions or feelings might be kept hidden. The state of affairs in your love life could be somewhat volatile, and misunderstandings might lead to strains in your relationship.\n" +
                    "\n If you are embarking on a new relationship, it's important to maintain emotional distance and avoid putting undue pressure on your partner. During this time, practicing self-discipline will be necessary. Try not to let your ego get in the way of love. While there may be challenges in love, you'll be fully committed to strengthening your relationships.\n" +
                    "\n Moreover, those seeking love might find their true love this year. The beginning of new relationships could occur in the workplace or college. Give time to your partner and make an effort to understand their feelings. Learn what your partner desires from the relationship. This year, several opportunities may arise where you can recognize your true love. However, it's essential not to engage in actions that could create difficulties in your romantic relationships.",
            "The health of Pisces individuals might be a bit sluggish this year, so you'll need to pay special attention to your well-being. If you focus on this aspect, health-related issues should not trouble you. To keep yourself fit, you can practice yoga, exercise, and other health routines. Maintain a healthy daily routine and ensure you get enough sleep. Meditation practices can help keep your mental state stable.\n" +
                    "\n This year, you may encounter digestive problems, so avoid eating stale food and reduce your consumption of fried and oily items. May and June will be good for your health, but you might face some health troubles in January, March, and September. If you experience any health issues, it's essential to consult a doctor immediately, as neglecting your health can be costly.\n" +
                    "\n Mentally, you might experience restlessness or unknown fears. Personal issues could also lead to mental stress. To overcome mental tension, seek entertainment. If you have a desire to travel, consider visiting a hill station.",
                    ""
    };
}
